spring.application.name: warehouse
grpc:
 enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: storer
    password: foryoureyes
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
management:
  port: 8081

validation-svc:
  hostname: "localhost"
  port: 7000
