version: '3.1'
services:
  db:
    build: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
       - 8080:8080
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
  inventarioserver:
    build: build/libs
    ports:
      - 7000:7000
    environment:
      GRPC_ADDRESS: inventarioServer
      GRPC_PORT: 7000
      RABBIT_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
