version: '3.3'
services:
  db:
    build: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer:4.3.1
    ports:
       - 8080:8080
  rabbitmq:
    image: rabbitmq:3.6.12-management
    ports:
      - 15672:15672
  inventarioserver:
    build: build/libs
    ports:
      - 6565:6565
    environment:
      RABBIT_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
