version: '3.3'
services:
  db:
    build: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer:4.3.1
    ports:
       - 8080:8080
  rabbitmq:
    image: rabbitmq:3.6.12-management
    ports:
      - 15672:15672
    environment:
      # Por default, RabbitMQ en Docker, escribe el log en la salida estandar.
      # Lo siguiente es para escribir los logs en archivos y evitar llenar la pantalla de logs.
      RABBITMQ_LOGS: /var/log/rabbitmq/rabbit.log
      RABBITMQ_SASL_LOGS: /var/log/rabbitmq/rabbit-sasl.log
  inventarioserver:
    build: build/libs
    ports:
      - 6565:6565
      - 8081:8081
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
