grpc:
 enabled: true
 servers:
   -
     # 127.0.0.1
     address: ${GRPC_ADDRESS}
     # 7000
     port: ${GRPC_PORT}

spring:
  rabbitmq:
    # localhost
    host: ${RABBIT_HOST}
    # 5672
    port: ${RABBIT_PORT}
    # guest
    username: ${RABBIT_USER}
    # guest
    password: ${RABBIT_PASS}
  datasource:
    # jdbc:postgresql://localhost:5432/mydb
    url: ${POSTGRES_URL}
    # postgres
    username: ${POSTGRES_USER}
    # example
    password: ${POSTGRES_PASS}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    generate-ddl: true