grpc:
 enabled: true
 servers:
   -
     address: 127.0.0.1
     port: 7000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: example
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true